<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PropFirmController extends Controller
{
    public function index()
    {
        $propFirms = $this->getPropFirmsData();
        return view('prop_firms.index', compact('propFirms'));
    }

    private function getPropFirmsData()
    {
        return [
            [
                'name' => 'FTMO',
                'logo' => 'ftmo',
                'rating' => 4.6,
                'reviews' => 149,
                'country' => 'Czech Republic',
                'flag' => 'cz',
                'years' => '10+',
                'assets' => ['Crypto', 'Energy', 'FX', 'Indices', 'Metals', 'Stocks'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 400000,
                'promo' => '€66 OFF',
                'description' => 'One of the most established prop firms with excellent reputation and high payouts.',
                'features' => ['No time limits', 'Scaling plan', 'High profit splits', 'Multiple account sizes']
            ],
            [
                'name' => 'The5ers',
                'logo' => 'the5ers',
                'rating' => 4.8,
                'reviews' => 882,
                'country' => 'Israel',
                'flag' => 'il',
                'years' => '9',
                'assets' => ['Crypto', 'Energy', 'FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 615000,
                'promo' => '5% OFF',
                'description' => 'Innovative prop firm with unique scaling system and excellent support.',
                'features' => ['Scaling program', 'No daily drawdown', 'Flexible rules', 'Fast payouts']
            ],
            [
                'name' => 'E8 Markets',
                'logo' => 'e8',
                'rating' => 4.8,
                'reviews' => 382,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '3',
                'assets' => ['Crypto', 'Energy', 'FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 2400000,
                'promo' => '5% OFF',
                'description' => 'High-capacity prop firm with up to $2.4M funding and excellent conditions.',
                'features' => ['Highest funding', 'No time limits', 'Scaling plan', 'Multiple platforms']
            ],
            [
                'name' => 'FundingPips',
                'logo' => 'fundingpips',
                'rating' => 4.4,
                'reviews' => 690,
                'country' => 'United Arab Emirates',
                'flag' => 'ae',
                'years' => '2',
                'assets' => ['Crypto', 'Energy', 'FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 300000,
                'promo' => '5% OFF',
                'description' => 'Fast-growing prop firm with competitive conditions and quick payouts.',
                'features' => ['Fast payouts', 'No daily drawdown', 'Scaling program', '24/7 support']
            ],
            [
                'name' => 'FundedNext',
                'logo' => 'fundednext',
                'rating' => 4.5,
                'reviews' => 523,
                'country' => 'United Arab Emirates',
                'flag' => 'ae',
                'years' => '3',
                'assets' => ['Crypto', 'Energy', 'FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 300000,
                'promo' => '25% OFF',
                'description' => 'Popular prop firm with excellent profit splits and flexible trading rules.',
                'features' => ['High profit splits', 'No daily drawdown', 'Scaling program', 'Multiple account sizes']
            ],
            [
                'name' => 'MyForexFunds',
                'logo' => 'myforexfunds',
                'rating' => 4.7,
                'reviews' => 1200,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '4',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 500000,
                'promo' => '10% OFF',
                'description' => 'Leading prop firm with excellent reputation and high success rates.',
                'features' => ['High success rate', 'No daily drawdown', 'Scaling program', 'Fast payouts']
            ],
            [
                'name' => 'TopStep',
                'logo' => 'topstep',
                'rating' => 4.3,
                'reviews' => 890,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '12',
                'assets' => ['FX', 'Indices', 'Metals', 'Futures'],
                'platforms' => ['NinjaTrader', 'TradingView'],
                'maxAllocation' => 150000,
                'promo' => 'Free Trial',
                'description' => 'Pioneer in prop trading with comprehensive evaluation process.',
                'features' => ['Free trial', 'Educational content', 'Scaling program', 'Professional support']
            ],
            [
                'name' => 'Apex Trader Funding',
                'logo' => 'apex',
                'rating' => 4.5,
                'reviews' => 650,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '6',
                'assets' => ['Futures', 'Indices', 'Metals', 'Energy'],
                'platforms' => ['NinjaTrader', 'TradingView'],
                'maxAllocation' => 300000,
                'promo' => '20% OFF',
                'description' => 'Futures-focused prop firm with excellent conditions and support.',
                'features' => ['Futures focus', 'No daily drawdown', 'Scaling program', 'Fast payouts']
            ],
            [
                'name' => 'SurgeTrader',
                'logo' => 'surge',
                'rating' => 4.4,
                'reviews' => 420,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '3',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 250000,
                'promo' => '15% OFF',
                'description' => 'Fast-growing prop firm with competitive conditions and quick evaluation.',
                'features' => ['Quick evaluation', 'No daily drawdown', 'Scaling program', '24/7 support']
            ],
            [
                'name' => 'Blue Guardian',
                'logo' => 'blueguardian',
                'rating' => 4.6,
                'reviews' => 380,
                'country' => 'United Kingdom',
                'flag' => 'gb',
                'years' => '4',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 200000,
                'promo' => '12% OFF',
                'description' => 'UK-based prop firm with excellent conditions and professional support.',
                'features' => ['UK regulated', 'No daily drawdown', 'Scaling program', 'Professional support']
            ],
            [
                'name' => 'Traders Central',
                'logo' => 'traderscentral',
                'rating' => 4.3,
                'reviews' => 290,
                'country' => 'Australia',
                'flag' => 'au',
                'years' => '5',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 150000,
                'promo' => '8% OFF',
                'description' => 'Australian prop firm with solid reputation and good trading conditions.',
                'features' => ['Australian regulated', 'No daily drawdown', 'Scaling program', 'Educational resources']
            ],
            [
                'name' => 'Fidelcrest',
                'logo' => 'fidelcrest',
                'rating' => 4.5,
                'reviews' => 520,
                'country' => 'Cyprus',
                'flag' => 'cy',
                'years' => '3',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 400000,
                'promo' => '18% OFF',
                'description' => 'European prop firm with excellent conditions and multiple account options.',
                'features' => ['EU regulated', 'No daily drawdown', 'Scaling program', 'Multiple platforms']
            ],
            [
                'name' => 'The Trading Pit',
                'logo' => 'tradingpit',
                'rating' => 4.4,
                'reviews' => 340,
                'country' => 'Germany',
                'flag' => 'de',
                'years' => '4',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 200000,
                'promo' => '10% OFF',
                'description' => 'German prop firm with professional approach and excellent support.',
                'features' => ['German regulated', 'No daily drawdown', 'Scaling program', 'Professional support']
            ],
            [
                'name' => 'City Traders Imperium',
                'logo' => 'citytraders',
                'rating' => 4.2,
                'reviews' => 280,
                'country' => 'United Kingdom',
                'flag' => 'gb',
                'years' => '3',
                'assets' => ['FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 100000,
                'promo' => '6% OFF',
                'description' => 'UK-based prop firm with focus on traditional forex trading.',
                'features' => ['UK regulated', 'No daily drawdown', 'Scaling program', 'Educational content']
            ],
            [
                'name' => 'TFT (The Funded Trader)',
                'logo' => 'tft',
                'rating' => 4.6,
                'reviews' => 780,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '2',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 400000,
                'promo' => '22% OFF',
                'description' => 'Rapidly growing prop firm with excellent conditions and fast payouts.',
                'features' => ['Fast payouts', 'No daily drawdown', 'Scaling program', '24/7 support']
            ],
            [
                'name' => 'Lux Trading Firm',
                'logo' => 'lux',
                'rating' => 4.3,
                'reviews' => 190,
                'country' => 'Luxembourg',
                'flag' => 'lu',
                'years' => '2',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 150000,
                'promo' => '14% OFF',
                'description' => 'Luxembourg-based prop firm with European regulations and good conditions.',
                'features' => ['EU regulated', 'No daily drawdown', 'Scaling program', 'Professional support']
            ],
            [
                'name' => 'True Forex Funds',
                'logo' => 'trueforex',
                'rating' => 4.4,
                'reviews' => 450,
                'country' => 'United Kingdom',
                'flag' => 'gb',
                'years' => '4',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 300000,
                'promo' => '16% OFF',
                'description' => 'UK prop firm with excellent reputation and comprehensive trading opportunities.',
                'features' => ['UK regulated', 'No daily drawdown', 'Scaling program', 'Multiple platforms']
            ],
            [
                'name' => 'Smart Prop Trader',
                'logo' => 'smartprop',
                'rating' => 4.1,
                'reviews' => 320,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '3',
                'assets' => ['FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 200000,
                'promo' => '11% OFF',
                'description' => 'US-based prop firm with smart evaluation process and good conditions.',
                'features' => ['Smart evaluation', 'No daily drawdown', 'Scaling program', 'Educational resources']
            ],
            [
                'name' => 'Traders With Edge',
                'logo' => 'tradersedge',
                'rating' => 4.5,
                'reviews' => 410,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '5',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5', 'cTrader'],
                'maxAllocation' => 250000,
                'promo' => '13% OFF',
                'description' => 'US prop firm with edge-focused trading approach and excellent support.',
                'features' => ['Edge trading', 'No daily drawdown', 'Scaling program', 'Professional support']
            ],
            [
                'name' => 'OneUp Trader',
                'logo' => 'oneup',
                'rating' => 4.2,
                'reviews' => 350,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '4',
                'assets' => ['Futures', 'Indices', 'Metals'],
                'platforms' => ['NinjaTrader', 'TradingView'],
                'maxAllocation' => 150000,
                'promo' => '9% OFF',
                'description' => 'Futures-focused prop firm with excellent evaluation process.',
                'features' => ['Futures focus', 'No daily drawdown', 'Scaling program', 'Educational content']
            ],
            [
                'name' => 'Leeloo Trading',
                'logo' => 'leeloo',
                'rating' => 4.4,
                'reviews' => 280,
                'country' => 'United Kingdom',
                'flag' => 'gb',
                'years' => '3',
                'assets' => ['FX', 'Indices', 'Metals', 'Crypto'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 200000,
                'promo' => '17% OFF',
                'description' => 'UK prop firm with innovative approach and excellent trading conditions.',
                'features' => ['Innovative approach', 'No daily drawdown', 'Scaling program', '24/7 support']
            ],
            [
                'name' => 'Trading Fund',
                'logo' => 'tradingfund',
                'rating' => 4.3,
                'reviews' => 240,
                'country' => 'United States',
                'flag' => 'us',
                'years' => '2',
                'assets' => ['FX', 'Indices', 'Metals'],
                'platforms' => ['MT4', 'MT5'],
                'maxAllocation' => 100000,
                'promo' => '7% OFF',
                'description' => 'US prop firm with focus on consistent trading and risk management.',
                'features' => ['Risk management', 'No daily drawdown', 'Scaling program', 'Educational resources']
            ]
        ];
    }
}
